#
# Webapp API service for Development
#

FROM node:10.14-alpine

# NPM Install for building
WORKDIR /usr/src/app
ADD package.json /usr/src/app/package.json
RUN npm install

# Copy source files:
WORKDIR /usr/src/app
ADD index.js /usr/src/app
ADD index.dev.js /usr/src/app
ADD .babelrc /usr/src/app
ADD .babelrc /usr/src/app
ADD .env /usr/src/app
ADD .eslintrc /usr/src/app
ADD .eslintignore /usr/src/app
ADD webpack.config.extend.js /usr/src/app
ADD webpackDevServer.config.extend.js /usr/src/app
ADD ssr /usr/src/app/ssr
ADD src /usr/src/app/src
ADD public /usr/src/app/public

# Default environment configuration:
EXPOSE 8080
EXPOSE 3000

#CMD ./node_modules/.bin/nodemon --watch ssr --watch build -e js index.dev.js
